baseURL: https://aafu.pages.dev/
# Uncomment below to use aafu as hugo theme. See instructions in README.md
# theme: aafu
languageCode: en-us
build:
  writeStats: true
params:
  title: Michelle's Personal Website
  author: Darshan Baral
  description: Website title
  copyright: >-
    powered by [hugo](https://gohugo.io/) & deployed on
    [Cloudflare](https://www.cloudflare.com/)
  theme:
    mainTheme: dark
    showAttribute: true
    singlePage: false
  favicons:
    use: true
    metas: |2-
              <link rel="apple-touch-icon" sizes="180x180" href="apple-touch-icon.png">
              <link rel="icon" type="image/png" sizes="32x32" href="favicon-32x32.png">
              <link rel="icon" type="image/png" sizes="16x16" href="favicon-16x16.png">
              <link rel="manifest" href="site.webmanifest">
              <link rel="mask-icon" href="safari-pinned-tab.svg" color="#252627">
              <link rel="shortcut icon" href="favicon.ico">

  profile:
    name: "Michelle Ordonez Campos"
    tagline: Software Engineering Intern
    location: "NY, USA"
    photo: profile.jpg
  social:
    title: Links
    list:
      - icon: fab fa-linkedin-in
        url: "https://www.linkedin.com/in/mordonez719/"
        title: LinkedIn
      - icon: fab fa-github
        url: "https://github.com/mordonez719"
        title: GitHub
  showInAccordion:
    - item: aboutme
      expand: true
    - item: experience
    - item: education
    - item: project
    - item: skill
    - item: hobby
  aboutme:
    title: About Me
    icon: fas fa-user
    description: I am currently a **second-year undergraduate** student studying computer science at *Northwestern University* with a passion for expanding education accessibility across the world.
  experience:
    title: Experiences
    icon: fas fa-briefcase
    list:
      - position: Software Engineering Intern
        dates: Jun 2024 - Aug 2024
        company: "Meta"
        details: |1-
          - Built 4 web applications employing a range of technologies including **React, Node.js, Express, and PostgreSQL**
          - Cleaned dead code from the company codebase, improving readability while preserving functionality
          - Developed full-stack technical skills through rigorous project-centered orientation
  education:
    title: Education
    icon: fas fa-graduation-cap
    list:
      - degree: B.S. in Computer Science
        college: Northwestern University
        dates: 2023 - 2027
  project:
    title: Projects
    icon: fas fa-project-diagram
    list:
      - title: HealthHub
        description: |1-
          - Utilized **React** and **Node.js** to create an interface for users to create workouts and meal plans
          - Integrated password encryption, protecting user data and privacy
          - Implemented social interaction, allowing users to manage friends and share creations
      - title: Cayley's Table Algorithm
        description: |1-
          - Used Python to generate a Cayley Table of the *group S3*, reducing the team’s analyzation time of symmetry, permutations, and relationships
      - title: Liquid Loophole
        description: |1-
          - Designed an automatic plastic draining system to improve on current recycling processes
          - Scaled prototype showed full accuracy in differentiating plastic from other materials for draining, sorting the input stream at a rate of 0.5 items/second
  skill:
    title: Skills
    panelId: skill-panel
    icon: fas fa-cogs
    list:
      - skill: "Python, C, C++"
        skillrating: 90 
      - skill: "React, Node.js, Express, PostgreSQL"
        skillrating: 90
      - skill: "Spanish"
        skillrating: 80
